CREATE TABLE IF NOT EXISTS `Cases` (
  `id` VARCHAR(36) PRIMARY KEY NOT NULL DEFAULT (uuid()),
  `case_id` VARCHAR(36) NOT NULL DEFAULT (uuid()),
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `scenery` VARCHAR(255) NOT NULL,
  `patient_id` VARCHAR(36),
  `monitoring_id` VARCHAR(36),
  `users_id` VARCHAR(36) NOT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);
